image:
  file: .devcontainer/Gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: private
tasks:
  - name: Set up workspace
    init: npm install
  - name: Vite DevServer
    command: npm run dev
vscode:
  extensions:
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
github:
  prebuilds:
    branches: true
    addBadge: true
    addCheck: false
