image:
  file: .devcontainer/Dockerfile.gp
ports:
  - port: 3000
    onOpen: open-browser
    visibility: private
tasks:
  - name: Set up workspace
    init: npm install
  - name: React DevServer
    command: npm run devstart
vscode:
  extensions:
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
github:
  prebuilds:
    branches: true
    addBadge: true
    addCheck: false
