name: React Build

on:
  push:
    paths:
      - "src/**"
      - "public/**"
  pull_request:
    paths:
      - "src/**"
      - "public/**"

jobs:
  build:
    name: React Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies in CI mode
        run: npm ci

      - name: Build project
        run: npm run build
