name: Check Code Style

on:
  push:
    paths:
      - "src/**"
      - "public/**"
  pull_request:
    paths:
      - "src/**"
      - "public/**"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Install dependencies in CI mode
      #  run: npm ci

      - name: Check code style
        run: npx prettier --check src/ public/
