name: Check Code Style

on:
  push:
    paths:
      - "src/**"
      - "public/**"
  pull_request:
    paths:
      - "src/**"
      - "public/**"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check code style
        run: npm run prettier:ci
